## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

Создание случайного массива для заданий 1-2

In [6]:
random_number_generator = np.random.default_rng()
random_array = random_number_generator.integers(low=-10, high=10, size=15)

print(f'Random array: {random_array}')

Random array: [ -3   7  -4   9   1 -10   8 -10  -7  -2   2  -4  -5  -3   0]


**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [7]:
def opposite_sign(array):
  random_array_copy_1 = np.copy(array)
  print(f'Copied array: {random_array_copy_1}')
  condition_mask = (array >= 3) & (array <= 8)
  random_array_copy_1[condition_mask] = random_array_copy_1[condition_mask] *(-1)
  print(f'Result: {random_array_copy_1}')

opposite_sign(random_array)

Copied array: [ -3   7  -4   9   1 -10   8 -10  -7  -2   2  -4  -5  -3   0]
Result: [ -3  -7  -4   9   1 -10  -8 -10  -7  -2   2  -4  -5  -3   0]


**2.** Заменить максимальный элемент случайного массива на 0

In [8]:
def replace_max_elem(array):
  random_array_copy_2 = np.copy(array)
  print(f'Copied array: {random_array_copy_2}')
  max_elem = random_array_copy_2.max()
  print(f'Max element: {max_elem}')
  condition_mask = random_array_copy_2 == max_elem
  random_array_copy_2[condition_mask] = 0
  print(f'Result: {random_array_copy_2}')

replace_max_elem(random_array)

Copied array: [ -3   7  -4   9   1 -10   8 -10  -7  -2   2  -4  -5  -3   0]
Max element: 9
Result: [ -3   7  -4   0   1 -10   8 -10  -7  -2   2  -4  -5  -3   0]


Создание двумерного массива для задания 3

In [9]:
random_2d_array_1 = random_number_generator.integers(low=-5, high=10, size=(3,4))
print('First 2d array: ', *random_2d_array_1)
random_2d_array_2 = random_number_generator.integers(low=-5, high=10, size=(3,4))
print('Second 2d array: ', *random_2d_array_2)

First 2d array:  [-4  2 -4  8] [ 8 -4 -4  4] [-5  4 -2 -1]
Second 2d array:  [ 2  0  9 -1] [8 6 8 9] [ 1 -1  3 -5]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

Со сплющиванием массивов

In [10]:
from itertools import product

def cartezian_product(array_2d_1, array_2d_2):
  flatted_array_1 = np.ravel(array_2d_1)
  flatted_array_2 = np.ravel(array_2d_2)
  pares_iterator = product(flatted_array_1, flatted_array_2)
  result = np.array(list(pares_iterator))
  print(f'Result of cartesian product: {result}')

cartezian_product(random_2d_array_1, random_2d_array_2)

Result of cartesian product: [[-4  2]
 [-4  0]
 [-4  9]
 [-4 -1]
 [-4  8]
 [-4  6]
 [-4  8]
 [-4  9]
 [-4  1]
 [-4 -1]
 [-4  3]
 [-4 -5]
 [ 2  2]
 [ 2  0]
 [ 2  9]
 [ 2 -1]
 [ 2  8]
 [ 2  6]
 [ 2  8]
 [ 2  9]
 [ 2  1]
 [ 2 -1]
 [ 2  3]
 [ 2 -5]
 [-4  2]
 [-4  0]
 [-4  9]
 [-4 -1]
 [-4  8]
 [-4  6]
 [-4  8]
 [-4  9]
 [-4  1]
 [-4 -1]
 [-4  3]
 [-4 -5]
 [ 8  2]
 [ 8  0]
 [ 8  9]
 [ 8 -1]
 [ 8  8]
 [ 8  6]
 [ 8  8]
 [ 8  9]
 [ 8  1]
 [ 8 -1]
 [ 8  3]
 [ 8 -5]
 [ 8  2]
 [ 8  0]
 [ 8  9]
 [ 8 -1]
 [ 8  8]
 [ 8  6]
 [ 8  8]
 [ 8  9]
 [ 8  1]
 [ 8 -1]
 [ 8  3]
 [ 8 -5]
 [-4  2]
 [-4  0]
 [-4  9]
 [-4 -1]
 [-4  8]
 [-4  6]
 [-4  8]
 [-4  9]
 [-4  1]
 [-4 -1]
 [-4  3]
 [-4 -5]
 [-4  2]
 [-4  0]
 [-4  9]
 [-4 -1]
 [-4  8]
 [-4  6]
 [-4  8]
 [-4  9]
 [-4  1]
 [-4 -1]
 [-4  3]
 [-4 -5]
 [ 4  2]
 [ 4  0]
 [ 4  9]
 [ 4 -1]
 [ 4  8]
 [ 4  6]
 [ 4  8]
 [ 4  9]
 [ 4  1]
 [ 4 -1]
 [ 4  3]
 [ 4 -5]
 [-5  2]
 [-5  0]
 [-5  9]
 [-5 -1]
 [-5  8]
 [-5  6]
 [-5  8]
 [-5  9]
 [-5  1]
 [-5 -1]
 [-5  3]
 [-5 -5]

Без сплющивания массивов

In [11]:
def cartezian_product_2(array_2d_1, array_2d_2):
  pares_iterator = product(array_2d_1, array_2d_2)
  result = np.array(list(pares_iterator))
  print(f'Result of cartesian product: {result}')

cartezian_product_2(random_2d_array_1, random_2d_array_2)

Result of cartesian product: [[[-4  2 -4  8]
  [ 2  0  9 -1]]

 [[-4  2 -4  8]
  [ 8  6  8  9]]

 [[-4  2 -4  8]
  [ 1 -1  3 -5]]

 [[ 8 -4 -4  4]
  [ 2  0  9 -1]]

 [[ 8 -4 -4  4]
  [ 8  6  8  9]]

 [[ 8 -4 -4  4]
  [ 1 -1  3 -5]]

 [[-5  4 -2 -1]
  [ 2  0  9 -1]]

 [[-5  4 -2 -1]
  [ 8  6  8  9]]

 [[-5  4 -2 -1]
  [ 1 -1  3 -5]]]


Создание массивов для задания 4

In [12]:
B = np.array([
    [1, 5],
    [9, 5]
])

A = np.array([
    [9, 1, 5],
    [1, 5, 2],
    [5, 9, 3],
    [5, 8, 4],
    [0, 6, 7],
    [9, 9, 9],
    [2, 4, 6],
    [3, 7, 8]
])

print('Array A: ', *A)
print('Array B: ', *B)

Array A:  [9 1 5] [1 5 2] [5 9 3] [5 8 4] [0 6 7] [9 9 9] [2 4 6] [3 7 8]
Array B:  [1 5] [9 5]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [13]:
def find_lines(array_a, array_b):
  lines = []
  for element in array_a:
    in_line = np.isin(array_b, element) 
    all_elements_of_row_in_line = np.all(in_line, axis=1)
    all_elements_of_b_in_line = np.all(all_elements_of_row_in_line)
    if all_elements_of_b_in_line:
      lines.append(element)

  result = np.array(lines)
  print('Result: ', *result)

find_lines(A, B)

Result:  [9 1 5]


Создание матрицы для задания 5

In [38]:
array_with_same_values_in_rows = np.array([
  [1, 2, 3], 
  [4, 4, 4],
  [10, 11, 12],
  [11, 11, 21],
  [-2, -2, -2], 
  [1, 2, 3], 
  [11, 11, 11], 
  [7, 8, 9]
])

print('2D array with duplicates: ', *array_with_same_values_in_rows)

2D array with duplicates:  [1 2 3] [4 4 4] [10 11 12] [11 11 21] [-2 -2 -2] [1 2 3] [11 11 11] [7 8 9]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [39]:

def is_unique(row):
  return len(row) == len(np.unique(row))

def delite_rows_with_same_values(array_2d):
  filtered_mask = np.apply_along_axis(is_unique, axis=1, arr=array_2d)
  print('Mask: ', filtered_mask)
  result = array_2d[filtered_mask]
  print('Result: ', result)

delite_rows_with_same_values(array_with_same_values_in_rows)

Mask:  [ True False  True False False  True False  True]
Result:  [[ 1  2  3]
 [10 11 12]
 [ 1  2  3]
 [ 7  8  9]]


Создание двумерного массива с дубликатами для задания 6

In [40]:
array_with_duplicates = np.array([
  [1, 2, 3], 
  [4, 5, 6],
  [10, 11, 12],
  [11, 11, 21],
  [4, 5, 6], 
  [1, 2, 3], 
  [11, 11, 21], 
  [7, 8, 9]
])

print('2D array with duplicates: ', *array_with_duplicates)

2D array with duplicates:  [1 2 3] [4 5 6] [10 11 12] [11 11 21] [4 5 6] [1 2 3] [11 11 21] [7 8 9]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [41]:
def delite_duplicate_lines(array_2d):
  array_without_duplicates = np.unique(array_2d, axis=0)
  print('Array without duplicates: ', *array_without_duplicates)

delite_duplicate_lines(array_with_duplicates)

Array without duplicates:  [1 2 3] [4 5 6] [7 8 9] [10 11 12] [11 11 21]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

Реализация 1 

In [6]:
list_task_1 = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

def task_1_list(list_of_lists):
  result = 1
  number_of_rows = len(list_of_lists)
  number_of_columns = len(list_of_lists[0]) if number_of_rows > 0 else 0
  final_index = min(number_of_columns, number_of_rows)
  for i in range(final_index):
    elem = list_of_lists[i][i]
    if elem != 0:
      result *= elem

  print('Result: ', result)
  

task_1_list(list_task_1)

Result:  3


Реализация 2

In [2]:
rectangle_matrix = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

def task_1_numpy(rectangle_matrix):
  diagonal = np.diag(rectangle_matrix)
  conditional_mask = diagonal != 0
  non_zero_elements = diagonal[conditional_mask]
  result = np.prod(non_zero_elements)
  print('Result: ', result)

task_1_numpy(rectangle_matrix)

Result:  3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

Реализация 1

In [3]:
list_1 = [1, 2, 2, 4]
list_2 = [4, 2, 1, 2]

def check_multiset(list_1, list_2):
  if len(list_1) != len(list_2):
    return False
  return sorted(list_1) == sorted(list_2)

result = check_multiset(list_1, list_2)
print('Result: ', result)

Result:  True


Реализация 2

In [7]:
vector_1 = np.array([1, 2, 2, 4])
vector_2 = np.array([4, 2, 1, 2])

def check_multiset_numpy(vector_1, vector_2):
  if vector_1.size != vector_2.size:
    return False
  return np.array_equal(np.sort(vector_1), np.sort(vector_2))

result = check_multiset_numpy(vector_1, vector_2)
print('Result: ', result)

Result:  True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

Реализация 1

In [9]:
list_with_zeros = [6, 2, 0, 3, 0, 0, 5, 7, 0]

def max_element(list_with_zeros):
  max_elem = -float('inf')
  for i in range(1, len(list_with_zeros)):
    if list_with_zeros[i - 1] == 0:
      current_elem = list_with_zeros[i]

      if current_elem > max_elem:
        max_elem = current_elem
  
  if max_elem == -float('inf'):
    print('There is no 0 in a list')
  else:
    print('Max element: ', max_elem)

max_element(list_with_zeros)

Max element:  5


Реализация 2

In [8]:
vector_with_zeros = np.array([6, 2, 0, 3, 0, 0, 7, 0])

def max_element_numpy(vector_with_zeros):
  zeros = np.where(vector_with_zeros == 0)[0]
  elements_indexes = zeros + 1
  suitable_indexes = elements_indexes[elements_indexes < vector_with_zeros.size]
  suitable_elements = vector_with_zeros[suitable_indexes]
  if suitable_elements.size == 0:
    print('There is no 0 in a vector')
  else:
    max_elem = np.max(suitable_elements)
    print('Result: ', result)

max_element_numpy(vector_with_zeros)

Result:  True


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

Реализация 1

In [9]:
list_with_repetitions = [2, 2, 2, 3, 3, 3, 5]

def split_list(list_with_repetitions):
  if len(list_with_repetitions) == 0:
    print('Result: ', [], [])
  else: 
    unique_elems = set(list_with_repetitions)
    repetitions = []
    for elem in unique_elems:
      counter = 0
      for val in list_with_repetitions:
        if elem == val:
          counter += 1
      repetitions.append(counter)
    print('Result: ', list_with_repetitions, repetitions)

split_list(list_with_repetitions)

Result:  [2, 2, 2, 3, 3, 3, 5] [3, 3, 1]


Реализация 2

In [10]:
vector_with_repetitions = np.array([2, 2, 2, 3, 3, 3, 5])

def split_list_numpy(vector):
  if vector.size == 0:
    return np.array([]), np.array([])
  elements, repetitions = np.unique(vector, return_counts=True)
  return elements, repetitions
  
result = split_list_numpy(vector_with_repetitions)
print('Result: ', result) 

Result:  (array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

Реализация 1

In [19]:
import math
import timeit
from scipy.spatial.distance import cdist

number_of_rows = 700
number_of_dimensions = 30
number_of_runs = 4

selection_1_np = np.random.rand(number_of_rows, number_of_dimensions)
selection_2_np = np.random.rand(number_of_rows, number_of_dimensions)
selection_1 = selection_1_np.tolist()
selection_2 = selection_2_np.tolist()

def euclidean_distance_list(list_1, list_2):
    square_sum = 0
    for i in range(len(list_1)):
        square_sum += (list_1[i] - list_2[i]) ** 2
    return math.sqrt(square_sum)

def euclidean_distances_lists(first_selection, second_selection):
    result_matrix = []
    for row_x in first_selection:
        row_distances = []
        for row_y in second_selection:
            distance = euclidean_distance_list(row_x, row_y)
            row_distances.append(distance)
        result_matrix.append(row_distances)
    return result_matrix

list_time = timeit.timeit(lambda: euclidean_distances_lists(selection_1, selection_2), number=number_of_runs)
average_time_list = list_time / number_of_runs

scipy_time = timeit.timeit(lambda: cdist(selection_1_np, selection_2_np, metric='euclidean'), number=number_of_runs)
average_time_scipy = scipy_time / number_of_runs

result_list = euclidean_distances_lists(selection_1, selection_2)
result_1 = np.array(result_list) 

result_1 = euclidean_distances_lists(selection_1, selection_2)
#print('Result: ', result_1)
print('Numpy time: ', round(average_time_list, 2))
print('Scipy time: ', round(average_time_scipy, 2))

Numpy time:  2.99
Scipy time:  0.01


Реализация 2

In [20]:
import timeit
from scipy.spatial.distance import cdist

number_of_rows = 700
number_of_dimensions = 30
number_of_runs = 4
selection_1 = np.random.rand(number_of_rows, number_of_dimensions)
selection_2 = np.random.rand(number_of_rows, number_of_dimensions)

def euclidean_distances_numpy(first_selection, second_selection):
  first_squares_of_lengths = np.sum(np.square(first_selection), axis=1, keepdims=True)
  second_squares_of_lengths = np.sum(np.square(second_selection), axis=1, keepdims=True)
  dot_product = np.dot(first_selection, second_selection.T)
  square_distances = first_squares_of_lengths + second_squares_of_lengths.T - 2 * dot_product
  square_distances = np.maximum(square_distances, 0)
  return np.sqrt(square_distances)

numpy_time = timeit.timeit(lambda: euclidean_distances_numpy(selection_1, selection_2), number=number_of_runs)
average_time_numpy = numpy_time / number_of_runs

scipy_time = timeit.timeit(lambda: cdist(selection_1, selection_2, metric='euclidean'), number=number_of_runs)
average_time_scipy = scipy_time / number_of_runs

result_1 = euclidean_distances_numpy(selection_1, selection_2)
print('Result: ', result_1)
print('Numpy time: ', round(average_time_numpy, 2))
print('Scipy time: ', round(average_time_scipy, 2))

Result:  [[2.22735473 2.26334508 2.26789323 ... 2.43139938 2.24396192 2.42735942]
 [1.70731895 1.81033521 2.09355746 ... 1.82829938 2.32345685 2.07342434]
 [2.18113015 2.05310912 2.38083279 ... 1.99999922 2.33262836 1.92701515]
 ...
 [1.90415625 2.22516945 2.70961556 ... 2.0450583  2.51256716 2.35532465]
 [2.42349937 2.71729479 2.38231888 ... 2.02222571 2.49406718 2.55228799]
 [2.08604242 2.39178345 2.86494427 ... 1.84543329 2.43019832 2.51309157]]
Numpy time:  0.01
Scipy time:  0.01


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [52]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [53]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [54]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [55]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [56]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [57]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [58]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [59]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [60]:
# your code