## Упражнения по библиотеке Numpy

In [3]:
import numpy as np

Создание случайного массива для заданий 1-2

In [4]:
random_number_generator = np.random.default_rng()
random_array = random_number_generator.integers(low=-10, high=10, size=15)

print(f'Random array: {random_array}')

Random array: [ 3  2 -6  0  9 -2  3  7  8  9 -7  5  4 -5 -4]


**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [15]:
def opposite_sign(array):
  random_array_copy_1 = np.copy(array)
  print(f'Copied array: {random_array_copy_1}')
  for index, element in enumerate(random_array_copy_1):
    if element >= 3 and element <=8:
      opposite_element = element * (-1)
      random_array_copy_1[index] = opposite_element
  print(f'Result: {random_array_copy_1}')

opposite_sign(random_array)

Copied array: [ 3  2 -6  0  9 -2  3  7  8  9 -7  5  4 -5 -4]
Result: [-3  2 -6  0  9 -2 -3 -7 -8  9 -7 -5 -4 -5 -4]


**2.** Заменить максимальный элемент случайного массива на 0

In [16]:
def replace_max_elem(array):
  random_array_copy_2 = np.copy(array)
  print(f'Copied array: {random_array_copy_2}')
  max_elem = random_array_copy_2.max()
  print(f'Max element: {max_elem}')
  for index, element in enumerate(random_array_copy_2):
    if element == max_elem:
      random_array_copy_2[index] = 0
  print(f'Result: {random_array_copy_2}')

replace_max_elem(random_array)

Copied array: [ 3  2 -6  0  9 -2  3  7  8  9 -7  5  4 -5 -4]
Max element: 9
Result: [ 3  2 -6  0  0 -2  3  7  8  0 -7  5  4 -5 -4]


Создание двумерного массива для задания 3 и 6

In [17]:
random_2d_array_1 = random_number_generator.integers(low=-5, high=10, size=(3,4))
print('First 2d array: ', *random_2d_array_1)
random_2d_array_2 = random_number_generator.integers(low=-5, high=10, size=(3,4))
print('Second 2d array: ', *random_2d_array_2)

First 2d array:  [ 2 -2 -1 -2] [-4 -2  5  6] [ 8 -2  3  8]
Second 2d array:  [-3  9  2  7] [0 6 1 2] [ 0 -2  0  6]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

Со сплющиванием массивов

In [18]:
from itertools import product

def cartezian_product(array_2d_1, array_2d_2):
  flatted_array_1 = np.ravel(array_2d_1)
  flatted_array_2 = np.ravel(array_2d_2)
  pares_iterator = product(flatted_array_1, flatted_array_2)
  result = np.array(list(pares_iterator))
  print(f'Result of cartesian product: {result}')

cartezian_product(random_2d_array_1, random_2d_array_2)

Result of cartesian product: [[ 2 -3]
 [ 2  9]
 [ 2  2]
 [ 2  7]
 [ 2  0]
 [ 2  6]
 [ 2  1]
 [ 2  2]
 [ 2  0]
 [ 2 -2]
 [ 2  0]
 [ 2  6]
 [-2 -3]
 [-2  9]
 [-2  2]
 [-2  7]
 [-2  0]
 [-2  6]
 [-2  1]
 [-2  2]
 [-2  0]
 [-2 -2]
 [-2  0]
 [-2  6]
 [-1 -3]
 [-1  9]
 [-1  2]
 [-1  7]
 [-1  0]
 [-1  6]
 [-1  1]
 [-1  2]
 [-1  0]
 [-1 -2]
 [-1  0]
 [-1  6]
 [-2 -3]
 [-2  9]
 [-2  2]
 [-2  7]
 [-2  0]
 [-2  6]
 [-2  1]
 [-2  2]
 [-2  0]
 [-2 -2]
 [-2  0]
 [-2  6]
 [-4 -3]
 [-4  9]
 [-4  2]
 [-4  7]
 [-4  0]
 [-4  6]
 [-4  1]
 [-4  2]
 [-4  0]
 [-4 -2]
 [-4  0]
 [-4  6]
 [-2 -3]
 [-2  9]
 [-2  2]
 [-2  7]
 [-2  0]
 [-2  6]
 [-2  1]
 [-2  2]
 [-2  0]
 [-2 -2]
 [-2  0]
 [-2  6]
 [ 5 -3]
 [ 5  9]
 [ 5  2]
 [ 5  7]
 [ 5  0]
 [ 5  6]
 [ 5  1]
 [ 5  2]
 [ 5  0]
 [ 5 -2]
 [ 5  0]
 [ 5  6]
 [ 6 -3]
 [ 6  9]
 [ 6  2]
 [ 6  7]
 [ 6  0]
 [ 6  6]
 [ 6  1]
 [ 6  2]
 [ 6  0]
 [ 6 -2]
 [ 6  0]
 [ 6  6]
 [ 8 -3]
 [ 8  9]
 [ 8  2]
 [ 8  7]
 [ 8  0]
 [ 8  6]
 [ 8  1]
 [ 8  2]
 [ 8  0]
 [ 8 -2]
 [ 8  0]
 [ 8  6]

Без сплющивания массивов

In [19]:
def cartezian_product_2(array_2d_1, array_2d_2):
  pares_iterator = product(array_2d_1, array_2d_2)
  result = np.array(list(pares_iterator))
  print(f'Result of cartesian product: {result}')

cartezian_product_2(random_2d_array_1, random_2d_array_2)

Result of cartesian product: [[[ 2 -2 -1 -2]
  [-3  9  2  7]]

 [[ 2 -2 -1 -2]
  [ 0  6  1  2]]

 [[ 2 -2 -1 -2]
  [ 0 -2  0  6]]

 [[-4 -2  5  6]
  [-3  9  2  7]]

 [[-4 -2  5  6]
  [ 0  6  1  2]]

 [[-4 -2  5  6]
  [ 0 -2  0  6]]

 [[ 8 -2  3  8]
  [-3  9  2  7]]

 [[ 8 -2  3  8]
  [ 0  6  1  2]]

 [[ 8 -2  3  8]
  [ 0 -2  0  6]]]


Создание массивов для задания 4

In [20]:
B = np.array([
    [1, 5],
    [9, 5]
])

A = np.array([
    [9, 1, 5],
    [1, 5, 2],
    [5, 9, 3],
    [5, 8, 4],
    [0, 6, 7],
    [9, 9, 9],
    [2, 4, 6],
    [3, 7, 8]
])

print('Array A: ', *A)
print('Array B: ', *B)

Array A:  [9 1 5] [1 5 2] [5 9 3] [5 8 4] [0 6 7] [9 9 9] [2 4 6] [3 7 8]
Array B:  [1 5] [9 5]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [21]:
def find_lines(array_a, array_b):
  for element in array_a:
    contain_all_rows = True
    for elem in array_b:
      elements_in_line = np.isin(elem, element)
      all_elements = np.all(elements_in_line)
      if not all_elements:
        contain_all_rows = False
        break
    if contain_all_rows:
      print(f'Line: {element}')

find_lines(A, B)

Line: [9 1 5]


Создание матрицы для задания 5

In [27]:
array_with_same_values_in_rows = np.array([
  [1, 2, 3], 
  [4, 4, 4],
  [10, 11, 12],
  [11, 11, 21],
  [-2, -2, -2], 
  [1, 2, 3], 
  [11, 11, 11], 
  [7, 8, 9]
])

print('2D array with duplicates: ', *array_with_same_values_in_rows)

2D array with duplicates:  [1 2 3] [4 4 4] [10 11 12] [11 11 21] [-2 -2 -2] [1 2 3] [11 11 11] [7 8 9]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [29]:

def is_unique(row):
  return len(row) == len(np.unique(row))

def delite_rows_with_same_values(array_2d):
  filtered_mask = np.apply_along_axis(is_unique, axis=1, arr=array_2d)
  print('Mask: ', filtered_mask)
  result = array_2d[filtered_mask]
  print('Result: ', result)

delite_rows_with_same_values(array_with_same_values_in_rows)

Mask:  [ True False  True False False  True False  True]
Result:  [[ 1  2  3]
 [10 11 12]
 [ 1  2  3]
 [ 7  8  9]]


Создание двумерного массива с дубликатами для задания 6

In [ ]:
array_with_duplicates = np.array([
  [1, 2, 3], 
  [4, 5, 6],
  [10, 11, 12],
  [11, 11, 21],
  [4, 5, 6], 
  [1, 2, 3], 
  [11, 11, 21], 
  [7, 8, 9]
])

print('2D array with duplicates: ', *array_with_duplicates)

2D array with duplicates:  [1 2 3] [4 5 6] [10 11 12] [11 11 11] [4 5 6] [1 2 3] [11 11 11] [7 8 9]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [24]:
def delite_duplicate_lines(array_2d):
  array_without_duplicates = np.unique(array_2d, axis=0)
  print('Array without duplicates: ', *array_without_duplicates)

delite_duplicate_lines(array_with_duplicates)

Array without duplicates:  [1 2 3] [4 5 6] [7 8 9] [10 11 12] [11 11 11]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [47]:
# your code

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [48]:
# your code

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [49]:
# your code

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [50]:
# your code

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [51]:
# your code

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [52]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [53]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [54]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [55]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [56]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [57]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [58]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [59]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [60]:
# your code